//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    
     using Newtonsoft.Json;
    public partial class user_action
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int Act_ID { get; set; }
        public Nullable<bool> isPass { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ActionInfo ActionInfo { get; set; }
    }
}
