//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    
     using Newtonsoft.Json;
    public partial class WF_StepInfo
    {
        public int ID { get; set; }
        public Nullable<int> WF_InstanceID { get; set; }
        public string StepName { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<bool> IsStartStep { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public string StepResult { get; set; }
        public Nullable<short> DelFlag { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ParentStepID { get; set; }
        public Nullable<int> ChildStepID { get; set; }
        public Nullable<bool> IsEndStep { get; set; }
        public Nullable<int> ProcessBy { get; set; }
    
        public virtual WF_Instance WF_Instance { get; set; }
    }
}
